### PR TITLE
added friending feature

### PR DESCRIPTION
**Pull request by michaelcbarrett**
Just added an existing gem 'has_friendship' to give users the ability to friend

### CODE REVIEW

**Comment by churichard** [comment]
Looks good.

**Comment by mitchbregs** [comment]
What exactly does adding a friend mean? I know that's a pretty vague
question but what exactly is "friending" in terms of code-- does it just
create a relationship sort of thing between 2 users?

On Friday, January 1, 2016, Richard Chu notifications@github.com wrote:

> Merged #16 https://github.com/SpecialHaven/SpecialHaven/pull/16.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpecialHaven/SpecialHaven/pull/16#event-503865711.

## 

Mitch

**Comment by michaelcbarrett** [comment]
Yep, it creates a table in the database that basically links one user ID to another. To check if two people are friends, we look at the table to see if any row has both user IDs.

**Comment by mitchbregs** [comment]
Ok awesome that's really cool!

On Friday, January 1, 2016, michaelcbarrett notifications@github.com
wrote:

> Yep, it creates a table in the database that basically links one user ID
> to another. To check if two people are friends, we look at the table to see
> if any row has both user IDs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpecialHaven/SpecialHaven/pull/16#issuecomment-168352343
> .

## 

Mitch

**Comment by churichard** [comment]
It probably wouldn't be terrible to code up our own implementation of it. Another way we could do it would be to create a model called `Friendship` which would store two user IDs and a boolean to indicate whether or not the friend request has been accepted yet. A `user` would simply store a list of these `Friendship`s, which would be his/her friend list. To see if two people are friends, we just check one of the users' friend lists. This would probably be a more efficient way of doing it, since iterating through a friend list would be much quicker than iterating through an entire table of friendships, but it should be fine to keep it how Michael implemented it for now.

**Pull request merged**
