### PR TITLE
created a post model

### PR DESCRIPTION
**Pull request by michaelcbarrett**
#3

Here is what I have so far. Any tips/changes?

I have created a main Post model that has the following database columns: title, body, url, type, event_start_time, event_end_time, user_id (of the author), created_at, and updated_at. 

There are 4 models that inherit from the Post model: TextPost, VideoPost, LinkPost, ImagePost, EventPost. 

All posts require a title, user_id, and type. 
In addition, text posts require a body; video, link, and image posts require a URL; and event posts require an event_start_time and an event_end_time.

Example creation of text post:
user = User.new(first_name: "Test", last_name: "User", email: "user@example.com", password: "password", password_confirmation: "password")
user.save
user.text_posts.create(title: "Test Title", body: "Hello, world!")

All posts can be viewed in user.posts.all
All text posts can be viewed in user.text_posts.all

### CODE REVIEW

**Comment by churichard** [comment]
Can you have attributes such as `event_start_time` and `event_end_time` only be part of an `EventPost`? Abstraction-wise, that would be the best way to do it. That would also make it easier to add more attributes and post types later on.

So the ideal way to structure this would probably be the following:
- Post - title, body, user_id, type, created_at, updated_at
  - TextPost
  - VideoPost - url
  - LinkPost - url
  - ImagePost - url
  - EventPost - event_start_time, event_end_time, location

**Comment by churichard** [comment]
Also, when making pull requests, it's good to reference the issue that the pull request is solving. That'll make it so that when we merge the pull request, the issue is automatically closed.

**Comment by michaelcbarrett** [comment]
Ok, I'll start making that change to the code now. And I appreciate the tip, still learning

**Comment by churichard** [comment]
No problem man! Keep up the good work, you're doing great so far :)

**Comment by michaelcbarrett** [comment]
Just changed it to fit your smart suggestion. Each post type (TextPost, LinkPost ...) inherits all of the attributes and validations from the Post model, but each one has custom attributes and validations as well. Used the gem 'active_record-acts_as' for multiple table inheritance.

**Comment by churichard** [comment]
Sweet, great job on the changes!

Have you ever done rebasing before? There's an aspect of it that'll let you squash the three commits that you currently have into one commit. Basically, the point of it is to make it so that when we merge into develop, we have a clean and easily readable commit history, so if we ever discover any errors down the line and want to roll back to an earlier commit, we'll be able to tell which one we should revert to. On that note, also try to make your commit messages more concise.

Here's a tutorial that should be helpful with squashing commits: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by michaelcbarrett** [comment]
I think I've successfully rebased it. Very cool git feature. Thanks for including the tutorial and giving me those tips!

**Comment by churichard** [comment]
Awesome, everything looks good!

**Pull request merged**
