### PR TITLE
create timeline page

### PR DESCRIPTION
**Pull request by churichard**

### CODE REVIEW

**Comment by churichard** [comment]
When I click on a text post, it gives me an error:
`The action 'show' could not be found for TextPostsController`
This error also shows up for different types of posts, e.g. (`The action 'show' could not be found for ImagePostsController`). Please fix this.

**Comment by michaelcbarrett** [comment]
Got it, I'll add pages to display each of the posts.

**Comment by michaelcbarrett** [comment]
Should be error-free now. Added a basic display page for each post type. Not sure exactly what we'll want it to look like

**Comment by churichard** [comment]
It's fine if it looks really simplistic right now. I want to make sure we have all the information we want on the page, though. Here's some stuff that's still missing:
- ImagePost view is missing the body
- VideoPost view is missing the body
- EventPost view is missing the zip code
- LinkPost should display the body below the link on the timeline page
- If you create a LinkPost with a url like `google.com` (aka without http:// in front), clicking on the post fails

**Comment by michaelcbarrett** [comment]
I've cleaned up the timeline, added some missing pieces, and fixed the url problem by validating the url when inputted into the form.

**Comment by mitchbregs** [comment]
Good stuff brotha!

**Comment by churichard** [comment]
Sweet, good job!

**Pull request merged**
