### PR TITLE
create basic user profile

### PR DESCRIPTION
**Pull request by michaelcbarrett**
#5

### CODE REVIEW

**Comment by churichard** [comment]
This is breaking when I create a text post (or any other type of post) and then try navigating to my user profile. Here's a screenshot of the error:
http://puu.sh/ms6J6/57c267bfe5.png
Please fix.

**Comment by michaelcbarrett** [comment]
This will be resolved when the timeline is added. The missing partial template is in that pull request

**Comment by churichard** [comment]
Please rebase with develop.

**Comment by michaelcbarrett** [comment]
Rebased it. Page can be accessed by going to http://localhost:3000/users/1 (or whatever id #). Also, I'm just realizing that the first name, last name, and role aren't being stored when entered into the Sign Up form.

**Comment by churichard** [comment]
Can you fix that bug, and also add the name of the user to the profile page?

**Comment by michaelcbarrett** [comment]
The bug should be gone now. It doesn't show up for me anymore. The missing partial was added when the timeline was merged. And the name of the user will be displayed, but the sign-up form isn't saving the first and last name so it isn't displaying anything

**Comment by churichard** [comment]
I meant the bug where the signup form is not saving the first and last names, but we can make a new issue for that.

**Comment by michaelcbarrett** [comment]
Oh, got it, I'll check it out

**Pull request merged**
